### ISSUE TITLE
Copy bags from prod storage service to stage storage service for Digirati testing

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/storage-service#1026]
Could you please copy over the following bags into /digitised in the staging storage service so Tom has a variety of items to test that everything is working as expected on DDS/DLCS with the changes made for born digital access?

b16641097 - Video, no transcript
b16675630 - Video, with transcript (2-part multiple manifestation)
b16759230 - Video, expressed as multiple manifestation, but only one manifestation present
b17307922 - Audio, MP3
b19291449 - Manuscript with structure (TOC)
b20641151 - A very large archive (5661 images) without access control
b24963215 - A very large archive (6320 images) with access control
b24990796 - A work with a very large number of volumes (66 manifestations, 10,136 images)
b29524404 - Audio Multiple Manifestation (interview with PDF transcript)

**Comment by alexwlchan** [comment]
Ingests now in flight:

b16641097 / https://wellcome-ingest-inspector.glitch.me/ingests/4a2ff1dd-6444-4316-a1cc-416a22981858
b16675630 / https://wellcome-ingest-inspector.glitch.me/ingests/0a06593f-d35f-437e-ba4e-c972e2eca5e5
b16759230 / https://wellcome-ingest-inspector.glitch.me/ingests/f8c848c5-d356-4e8a-9b4c-5142f8c64ce3
b17307922 / https://wellcome-ingest-inspector.glitch.me/ingests/646a5dde-dffc-42f5-9898-d3a55eda766a
b19291449 / https://wellcome-ingest-inspector.glitch.me/ingests/7a3630f5-11d4-4270-9e62-a63763740a41
b20641151 / https://wellcome-ingest-inspector.glitch.me/ingests/f8ec3d85-7b68-444f-8876-1a17770e1842
b24963215 / https://wellcome-ingest-inspector.glitch.me/ingests/fc118ad3-1f27-4f45-9220-28f568b708f7
b24990796 / https://wellcome-ingest-inspector.glitch.me/ingests/651d864a-b84a-494e-b4fe-688292e3694b
b29524404 / https://wellcome-ingest-inspector.glitch.me/ingests/36d8606b-9260-4d63-9e90-5d78d013464d

**Comment by alexwlchan** [comment]
Stored successfully!
