### ISSUE TITLE
Copy more bags from prod to storage staging for Digirati

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/storage-service#1036]
https://github.com/wellcomecollection/storage-service/issues/1026

Much like the above ticket, Tom Crane needs some more items in storage staging to test with. However, I can't replicate these as the old a/v workflow doesn't exist anymore (and he specifically needs to make sure something works with these old METS). 

Can I get these copied over, please?

b16795532
b16673104
b30012132

**Comment by alexwlchan** [comment]
b30012132 – https://wellcome-ingest-inspector.glitch.me/ingests/e4cb6711-91fd-4c43-8dc1-b16e11a69215

**Comment by aray-wellcome** [comment]
These are all in now so you can turn off the EC2 instance. Thanks so much!

**Comment by alexwlchan** [comment]
Done, and EC2 instance terminated.
