### ISSUE TITLE
Delete bags from the storage service

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/storage-service#1109]
Per email from Ashley via Victoria to digital@wc.org 27 Nov 2023

> We’ll need to delete the bags for b33208827 and b33206144 in the digitsed storage space. 

See How to: https://github.com/wellcomecollection/storage-service/blob/main/docs/wellcome/completely-deleting-bags-from-the-storage-service.md?plain=1

**Comment by paul-butcher** [comment]
Requested permission to delete
