### ISSUE TITLE
Ingest corporate archive images

### ISSUE THREAD

**Issue by jcateswellcome** [wellcomecollection/storage-service#1126]
To support the accession of corporate photography into the archive, we would like to find a way to automatically ingest them in Archivematica.

https://www.notion.so/wellcometrust/Ingest-corporate-archive-images-09d2b2fc47b846a0a377900a6c7e386d?pvs=4

**Comment by paul-butcher** [comment]
Questions - just make sure I understand what it is I'm supposed to be doing:

1. Broadly speaking, this task is to write something that will...
   * iterate over the list of shoots, fetching each one from S3 as a folder - for each one
      * throw away the two redundant metadata files
      * create the appropriate metadata file for ingest
      * zip that all up
      * stick it in the right place on S3 for Archivematica to consume it
 2. There is something about "if a shoot needs to be broken up" - is that a size constraint?  If so, what is it, or do I have to just suck it and see?

**Comment by paul-butcher** [comment]
Regarding the Glacier aspect, I think we can [trigger a Bulk retrieval](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/restore_object.html#:~:text=Bulk retrievals) then use [Notifications](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/restore_object.html#:~:text=You can use Amazon S3 event notifications to notify you when a restore is initiated or completed) to trigger the next step

**Comment by paul-butcher** [comment]
There is a mention of this forming a "Repeatable pipeline is established for future ingests from S3 buckets", are there some other ingests expected in the near future?  Knowing this would help establish what kinds of options/parameters I might need to establish.

**Comment by jcateswellcome** [comment]
@paul-butcher my understanding is that the next, and most likely, ingest would be when the next year of corporate photography shoots is accessioned, so it is likely to be a largely similar/uniform kind of thing from a similar sort of place - if that is vaguely precise enough for now.

> There is a mention of this forming a "Repeatable pipeline is established for future ingests from S3 buckets", are there some other ingests expected in the near future? Knowing this would help establish what kinds of options/parameters I might need to establish.

**Comment by jcateswellcome** [comment]
> Questions - just make sure I understand what it is I'm supposed to be doing:
> 
> 1. Broadly speaking, this task is to write something that will...
>    
>    * iterate over the list of shoots, fetching each one from S3 as a folder - for each one
>      
>      * throw away the two redundant metadata files
>      * create the appropriate metadata file for ingest
>      * zip that all up
>      * stick it in the right place on S3 for Archivematica to consume it
> 2. There is something about "if a shoot needs to be broken up" - is that a size constraint?  If so, what is it, or do I have to just suck it and see?

1. yes, sounds right
2. I think suck it and see - this will come down to an Archivematica ingest limitations. I can try and find out from Ashley if there is a known or approximate number here.

**Comment by paul-butcher** [comment]
> There is a mention of this forming a "Repeatable pipeline is established for future ingests from S3 buckets", are there some other ingests expected in the near future? Knowing this would help establish what kinds of options/parameters I might need to establish.

That's great.  At the lowest level, the main thing I was wondering about is whether Glacier normally be involved, or if it's just going to be involved occasionally, might it be easiest to do that bit manually?  I don't need an answer on this, as I'll probably work it out as I go along.

**Comment by paul-butcher** [comment]
Are there any folders in this format that have are currently not in Glacier (i.e. less than 6 months old).  Not necessarily on the list.  Just  something where I can run a realistic not-quite-end-to-end test?

**Comment by jcateswellcome** [comment]
Don't know, assume not. I am out on Tuesday/Wednesday - so suggest you get in touch with Ashley?

**Comment by paul-butcher** [comment]
Ah. I've just spotted the minor wrinkle that both the buckets are in different accounts.  That's a little bit of a pain.

**Comment by paul-butcher** [comment]
Archivematica can be a bit flaky when ingesting large amounts of data.  We may need to do some kind of retry.

The limit on ingest is by number of files per packet - Ashley recalls that there is a maximum of probably 500.  I will set the maximum 250 in order to steer well clear of that.

**Comment by aray-wellcome** [comment]
If we want to practice this (and I think we should because it's really hard to delete things in storage if you mess up) then it'll need to go into the born-digital-accession folder of `/wellcomecollection-archivematica-staging-transfer-source`. No other subfolders are needed, just all zips into `born-digital-accessions`

The `/wellcomecollection-archivematica-staging-transfer-source` doesn't have a failed folder. You'll either get a success or failure log for each zip you put in. In the case of a failure, you can open the log and see what's wrong with it. The Lambda that produces the logs looks for issues with the metadata.csv and the structure of the zip I think. 

If you need to resubmit the zip because it failed in Archivematica, you can just copy the zip into the same location and it'll overwrite and the Lambda should pick it up again. 

If they fail for a legitimate reason then you should be able to pick it back up out of `/wellcomecollection-archivematica-staging-transfer-source` but we should check that it's not set to automatically clean up the successful items. I feel like Alex Chan did have some sort of cleanup code on this bucket but I have no idea if that's actually there and if it is, it's still working.

**Comment by alexwlchan** [comment]
> I feel like Alex Chan did have some sort of cleanup code on this bucket but I have no idea if that's actually there and if it is, it's still working.

The thing you're thinking of is https://github.com/wellcomecollection/archivematica-infrastructure/tree/main/lambdas/transfer_monitor

(Hello, I was looking up something in the ingest inspector code and decided to glance at the issues list for old times' sake. Glad to see Editorial Photography is finally moving storage service-ward 🥳)

**Comment by aray-wellcome** [comment]
What a surprise to see this notification! Thanks for digging out that Lambda info!

**Comment by jcateswellcome** [comment]
Marking this as complete

**Comment by alexwlchan** [comment]
Hooray! 🥳
